<?php

/**
 * @file
 * Link click count module file.
 */

/**
 * Implements hook_menu().
 */
function link_click_count_menu() {
  $items['link_click_count'] = array(
    'page callback' => 'link_click_count_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_views_api().
 */
function link_click_count_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'link_click_count'),
  );
}

/**
 * Callback function, to save clicks.
 */
function link_click_count_callback() {
  db_insert('link_click_count')->fields(array(
    'url' => $_GET["url"],
    'nid' => $_GET["nid"],
    'uid' => $GLOBALS['user']->uid,
    'date' => time(),
  ))->execute();
  drupal_goto($_GET["url"]);
}

/**
 * Implements hook_field_formatter_info().
 */
function link_click_count_field_formatter_info() {
  $info = array(
    'website' => array(
      'label' => t('Counts the click happened on this link.'),
      'field types' => array('link_field'),
      'description' => t('Counts the click happened on this link.'),
    ),
  );
  return $info;
}

/**
 * Implements hook_field_formatter_view().
 */
function link_click_count_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'website':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#theme' => 'link_click_count_link_field',
          '#url' => $item,
          '#node' => $entity,
        );
      }
      break;
  }
  return $element;
}

/**
 * Implements hook_theme().
 */
function link_click_count_theme() {
  return array(
    'link_click_count_link_field' => array(
      'template' => 'link_click_count_link_field',
      'variables' => array(
        'title' => NULL,
        'url' => NULL,
        'node' => NULL,
      ),
    ),
  );
}
